spring.application.name=u5-w3-d5
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.url=jdbc:postgresql://localhost:5432/OrganizzazioneEventi
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public

# JWT CONFIG
jwt.secret=${JWT_SECRET}
